# Generated by Django 4.0.6 on 2022-08-02 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_carcategory_shopcategory_blog_post_car_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='related_blog', to='app.carcategory', verbose_name='カテゴリ'),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='shop_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='related_shop', to='app.shopcategory', verbose_name='店カテゴリ'),
        ),
    ]
