# Generated by Django 4.0.6 on 2022-08-02 05:31

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_blog_post_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcategory',
            name='icon',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='images', verbose_name='アイコン'),
        ),
    ]
