# Generated by Django 4.0.6 on 2022-07-28 09:38

import accounts.models
from django.db import migrations, models
import django.utils.timezone
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email address')),
                ('user_id', models.CharField(max_length=10, null=True, unique=True, verbose_name='User ID (Alphanumeric only)')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='Name')),
                ('job', models.CharField(max_length=20, null=True, verbose_name='Job')),
                ('content', models.TextField(blank=True, max_length=200, verbose_name='Profile')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Create Day')),
                ('icon', stdimage.models.StdImageField(blank=True, null=True, upload_to='images', verbose_name='user icon')),
                ('instagram', models.CharField(blank=True, max_length=200, null=True, verbose_name='Instagram URL')),
                ('youtube', models.CharField(blank=True, max_length=200, null=True, verbose_name='YouTube URL')),
                ('twitter', models.CharField(blank=True, max_length=200, null=True, verbose_name='Twitter URL')),
                ('github', models.CharField(blank=True, max_length=200, null=True, verbose_name='Github URL')),
                ('site', models.CharField(blank=True, max_length=200, null=True, verbose_name='Your Web site URL')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
    ]
